
on:
  push:
    branches: ['gh_action_gh_container_registry']

env:
  REGISTRY: 
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
       name : [
          pymoab-py2-18.04,
          pymoab-py3-18.04,
          pymoab-visit-py2-18.04,
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.name }}/Dockerfile
          context: .
          push: true
          tags: ${{ matrix.name }}
 